import * as THREE from 'three';
import { createEntityPlacementRuntime } from '@/lib/runtime/entityPlacementRuntime';

const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
export function createAbilityPlaygroundScene(mount, ability, onEvent, onSpawn) {
  const scene = new THREE.Scene(); scene.background = new THREE.Color(0x0c0f13);
  const camera = new THREE.PerspectiveCamera(48, mount.clientWidth / mount.clientHeight, .1, 100); camera.position.set(0, 14, 12); camera.lookAt(0, 0, 0);
  const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(mount.clientWidth, mount.clientHeight); mount.appendChild(renderer.domElement);
  scene.add(new THREE.AmbientLight(0xffffff, .75)); const light = new THREE.DirectionalLight(0xffffff, 1); light.position.set(4, 10, 5); scene.add(light);
  const ground = new THREE.Mesh(new THREE.PlaneGeometry(22, 16), new THREE.MeshLambertMaterial({ color: 0x171b21 })); ground.rotation.x = -Math.PI / 2; scene.add(ground); scene.add(new THREE.GridHelper(22, 22, 0x4b5563, 0x242a32));
  const unit = (color, x) => { const g = new THREE.Group(); const body = new THREE.Mesh(new THREE.CapsuleGeometry(.45, .8, 5, 12), new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: .12 })); body.position.y = .85; g.add(body); g.position.x = x; scene.add(g); return { g, body }; };
  const hero = unit(0xb9c2cc, -4), enemy = unit(0xd97706, 4); enemy.body.userData.enemy = true;
  const range = clamp((ability?.targeting?.castRangeCm || 600) / 100, 2, 9); const rangeRing = new THREE.Mesh(new THREE.RingGeometry(range - .04, range, 64), new THREE.MeshBasicMaterial({ color: 0xb9c2cc, transparent: true, opacity: .35, side: THREE.DoubleSide })); rangeRing.rotation.x = -Math.PI / 2; rangeRing.position.y = .02; scene.add(rangeRing);
  const targetRing = new THREE.Mesh(new THREE.RingGeometry(.65, .78, 32), new THREE.MeshBasicMaterial({ color: 0xd97706, side: THREE.DoubleSide })); targetRing.rotation.x = -Math.PI / 2; targetRing.position.y = .03; scene.add(targetRing);
  const ray = new THREE.Raycaster(), pointer = new THREE.Vector2(), projectiles = [], timeouts = []; let destination = hero.g.position.clone(), disposed = false;
  const placement = createEntityPlacementRuntime(scene, onEvent, onSpawn);
  const point = e => { const r = renderer.domElement.getBoundingClientRect(); pointer.set((e.clientX-r.left)/r.width*2-1, -(e.clientY-r.top)/r.height*2+1); ray.setFromCamera(pointer,camera); return ray.intersectObject(ground)[0]?.point; };
  const onPointerMove = e => placement.preview(point(e));
  const onClick = e => { if (!placement.isActive) return; const p = point(e); if (p) placement.commit(p); };
  const onPointer = e => { const p = point(e); if (placement.isActive) { if (e.button === 2) { e.preventDefault(); placement.cancel(); } return; } if (e.button !== 2) return; e.preventDefault(); if (p) { destination.set(clamp(p.x,-10,10),0,clamp(p.z,-7,7)); onEvent('移动指令已提交'); } };
  renderer.domElement.addEventListener('pointermove', onPointerMove); renderer.domElement.addEventListener('click', onClick); renderer.domElement.addEventListener('pointerdown', onPointer); renderer.domElement.addEventListener('contextmenu', e => e.preventDefault());
  const cast = () => { const distance = hero.g.position.distanceTo(enemy.g.position); if (distance > range) return onEvent(`超出施放范围：${distance.toFixed(1)} / ${range.toFixed(1)}`); const orb = new THREE.Mesh(new THREE.SphereGeometry(.2,12,12), new THREE.MeshBasicMaterial({ color: 0xd97706 })); orb.position.copy(hero.g.position).setY(.9); scene.add(orb); projectiles.push({ mesh: orb, target: enemy.g.position.clone().setY(.9) }); onEvent(`施放 ${ability?.ability_id || 'Ability'} · ${ability?.exec?.items?.length || 0} Exec Items`); (ability?.exec?.items || []).forEach(item => timeouts.push(setTimeout(() => onEvent(`Tick ${item.tick}: ${item.kind}`), Math.max(0,item.tick)*40))); };
  const clock = new THREE.Clock(); const frame = () => { if(disposed)return; requestAnimationFrame(frame); const dt=Math.min(clock.getDelta(),.05); const delta=destination.clone().sub(hero.g.position); if(delta.length()>.05) hero.g.position.add(delta.normalize().multiplyScalar(dt*3)); rangeRing.position.x=hero.g.position.x; rangeRing.position.z=hero.g.position.z; targetRing.position.x=enemy.g.position.x; targetRing.position.z=enemy.g.position.z; for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i],d=p.target.clone().sub(p.mesh.position); if(d.length()<.25){scene.remove(p.mesh);projectiles.splice(i,1);onEvent('目标命中');}else p.mesh.position.add(d.normalize().multiplyScalar(dt*8));} renderer.render(scene,camera); }; frame();
  const resize=()=>{const w=mount.clientWidth,h=mount.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}; window.addEventListener('resize',resize);
  return { cast, beginPlacement: placement.begin, cancelPlacement: placement.cancel, clearPlaced: placement.clear, reset(){hero.g.position.set(-4,0,0);destination.copy(hero.g.position);}, dispose(){disposed=true;timeouts.forEach(clearTimeout);placement.dispose();window.removeEventListener('resize',resize);renderer.domElement.removeEventListener('pointermove',onPointerMove);renderer.domElement.removeEventListener('click',onClick);renderer.domElement.removeEventListener('pointerdown',onPointer);renderer.dispose();mount.removeChild(renderer.domElement);} };
}