import React from 'react';
import { Section, TextField, NumberField, SelectField, ListField } from '@/components/ludots/ui';
import JsonValueField from '@/components/ludots/JsonValueField';

export default function SimplePresentationDetails({ type, draft, patch }) {
  if (type === 'mesh') return <Section title="mesh_assets.json"><TextField label="ID" value={draft.asset_id} onChange={asset_id => patch({ asset_id })} /><SelectField label="Type" value={draft.type} options={['Primitive','Source','Procedural'].map(value=>({value,label:value}))} onChange={type=>patch({type})} />{draft.type==='Primitive' && <TextField label="Primitive Kind" value={draft.primitive_kind} onChange={primitive_kind=>patch({primitive_kind})} />}</Section>;
  if (type === 'material') return <Section title="material_assets.json"><TextField label="ID" value={draft.asset_id} onChange={asset_id=>patch({asset_id})} /><TextField label="Domain" value={draft.domain} onChange={domain=>patch({domain})} /><ListField label="Flags" value={draft.flags} onChange={flags=>patch({flags})} /></Section>;
  if (type === 'effect') return <Section title="effects.json · three.quarks"><TextField label="ID" value={draft.asset_id} onChange={asset_id=>patch({asset_id})} /><ListField label="Quarks JSON URIs" value={draft.source_uris} onChange={source_uris=>patch({source_uris})} /><NumberField label="Scale" value={draft.scale} onChange={scale=>patch({scale})} /><JsonValueField label="Quarks Config" value={draft.config} onChange={config=>patch({config})} /></Section>;
  if (type === 'text') return <Section title="text_tokens.json"><TextField label="ID" value={draft.token_id} onChange={token_id=>patch({token_id})} /><NumberField label="Arg Count" value={draft.arg_count} onChange={arg_count=>patch({arg_count})} /><TextField label="Default Locale" value={draft.default_locale} onChange={default_locale=>patch({default_locale})} /><JsonValueField label="Locales（locale → format string）" value={draft.locales} onChange={locales=>patch({locales})} /></Section>;
  if (type === 'clip') return <Section title="animation_clips.json"><TextField label="ID" value={draft.asset_id} onChange={asset_id=>patch({asset_id})} /><TextField label="Asset Kind" value={draft.asset_kind} onChange={asset_kind=>patch({asset_kind})} /><JsonValueField label="Locators [{backend_id, asset_ref, variant}]" value={draft.locators} onChange={locators=>patch({locators})} /><JsonValueField label="Blend Inputs [{x, y}]" value={draft.blend_inputs} onChange={blend_inputs=>patch({blend_inputs})} /></Section>;
  return <Section title="animator_controllers.json"><TextField label="ID" value={draft.controller_id} onChange={controller_id=>patch({controller_id})} /><NumberField label="Default State Index" value={draft.default_state_index} onChange={default_state_index=>patch({default_state_index})} /><JsonValueField label="States" value={draft.states} onChange={states=>patch({states})} /><JsonValueField label="Transitions" value={draft.transitions} onChange={transitions=>patch({transitions})} /></Section>;
}