import React from 'react';
import { RENDER_MODES } from '@/lib/quarks/quarksDocument';
const Toggle = ({ label, value, onChange }) => <label className="flex items-center gap-2 text-xs text-gray-300"><input type="checkbox" checked={!!value} onChange={e => onChange(e.target.checked)}/>{label}</label>;
export default function QuarksRenderingPanel({ ps, material, patch, patchMaterial }) {
  return <div className="space-y-3"><label className="block text-[10px] text-gray-400">渲染模式<select aria-label="渲染模式" value={ps.renderMode ?? 0} onChange={e => patch({ renderMode: Number(e.target.value) })} className="mt-1 h-8 w-full rounded border border-[#424A55] bg-[#0D0F14] px-2 text-xs">{RENDER_MODES.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    <div className="grid grid-cols-3 gap-2">{[['renderOrder','排序'],['uTileCount','横向帧'],['vTileCount','纵向帧']].map(([field,label]) => <label key={field} className="text-[10px] text-gray-400">{label}<input aria-label={label} type="number" min="0" value={ps[field] ?? (field === 'renderOrder' ? 0 : 1)} onChange={e => patch({ [field]: Number(e.target.value) })} className="mt-1 h-8 w-full rounded border border-[#424A55] bg-[#0D0F14] px-2 text-xs"/></label>)}</div>
    <div className="grid grid-cols-2 gap-2"><Toggle label="帧混合" value={ps.blendTiles} onChange={blendTiles => patch({ blendTiles })}/><Toggle label="软粒子" value={ps.softParticles} onChange={softParticles => patch({ softParticles })}/>{material && <><Toggle label="透明" value={material.transparent} onChange={transparent => patchMaterial({ transparent })}/><Toggle label="写入深度" value={material.depthWrite} onChange={depthWrite => patchMaterial({ depthWrite })}/></>}</div>
    {material && <label className="block text-[10px] text-gray-400">混合模式<select aria-label="混合模式" value={material.blending ?? 1} onChange={e => patchMaterial({ blending: Number(e.target.value) })} className="mt-1 h-8 w-full rounded border border-[#424A55] bg-[#0D0F14] px-2 text-xs"><option value="1">Normal</option><option value="2">Additive</option><option value="3">Subtractive</option><option value="4">Multiply</option></select></label>}
  </div>;
}